# Site settings
title: Jaskaran Veer Singh
description: 'Connect with him.'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jaskaran Veer Singh'
  email: jvsg1303@gmail.com
  twitter_username: impracticaljvsg
  facebook_username: profile.php?id=100009700660751
  github_username:  jvsg
  linkedin_username:  jaskaran-singh-726506102

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
